Support Ubuntu mantic
AdnanHodzic/displaylink-debian pull request #878
Opened 2023-11-16 10:49 UTC by jGleitz

On my machine, running Ubuntu 23.10 Mantic, the script works as-is and I can use my dock. Hence, I’d suggest adding mantic to the list of supported codenames, and addressing bugs as they are found.

2023-11-16 10:53 UTC, Barabazs requested changes
Thank you for your contribution.

Can you also update the README.md please (supported platforms)

2023-11-16 11:15 UTC, jGleitz commented
good point. done.

2023-11-16 14:03 UTC, Barabazs commented
It's not updated?

2023-11-18 20:21 UTC, jGleitz commented
> It's not updated?

Wtf, no idea what happened there. Now it’s really updated. Sorry for that!

2023-11-19 10:17 UTC, Barabazs approved these changes
Thank you!

2023-11-19 10:17 UTC, merged